name: lint-and-test
on: [workflow_dispatch, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: yarn install --frozen-lockfile
      - run: yarn check:types
      - run: yarn lint
      - run: yarn test:ci
